# Site settings
title: Javad Elmi | جواد علمی
email: hi@hosseinkarami.com
description: دانشجوی مهندسی کامپیوتر
baseurl: "http://elmi-javad.ir/"
url: "http://elmi-javad.ir"
twitter: _Karamii
github:  elmi-javad
behance: elmi-javad
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]
